// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/ocean386/common/orm/model"
)

func newBarData1h(db *gorm.DB, opts ...gen.DOOption) barData1h {
	_barData1h := barData1h{}

	_barData1h.barData1hDo.UseDB(db, opts...)
	_barData1h.barData1hDo.UseModel(&model.BarData1h{})

	tableName := _barData1h.barData1hDo.TableName()
	_barData1h.ALL = field.NewAsterisk(tableName)
	_barData1h.ID = field.NewInt64(tableName, "id")
	_barData1h.CurrencyID = field.NewString(tableName, "currency_id")
	_barData1h.BeginTime = field.NewInt64(tableName, "begin_time")
	_barData1h.OpenPrice = field.NewFloat64(tableName, "open_price")
	_barData1h.ClosePrice = field.NewFloat64(tableName, "close_price")
	_barData1h.HighPrice = field.NewFloat64(tableName, "high_price")
	_barData1h.LowPrice = field.NewFloat64(tableName, "low_price")
	_barData1h.BarType = field.NewString(tableName, "bar_type")
	_barData1h.SigType = field.NewInt64(tableName, "sig_type")
	_barData1h.PriceChange = field.NewFloat64(tableName, "price_change")
	_barData1h.PriceRange = field.NewFloat64(tableName, "price_range")
	_barData1h.PriceRangePrecent = field.NewFloat64(tableName, "price_range_precent")
	_barData1h.TriggerTime = field.NewInt64(tableName, "trigger_time")

	_barData1h.fillFieldMap()

	return _barData1h
}

// barData1h 时间粒度表-每小时
type barData1h struct {
	barData1hDo

	ALL               field.Asterisk
	ID                field.Int64   // 主键ID
	CurrencyID        field.String  // 币种ID
	BeginTime         field.Int64   // 开始时间
	OpenPrice         field.Float64 // 开盘价格
	ClosePrice        field.Float64 // 收盘价格
	HighPrice         field.Float64 // 最高价格
	LowPrice          field.Float64 // 最低价格
	BarType           field.String  // 时间粒度类型:默认值1m,1m/5m/15m/30m/1H/4H/12H/1D/1W/1M
	SigType           field.Int64   // 行情信号: 0-/, 1-上涨, 2-快速上涨, 3-爆涨, 4-下跌, 5-快速下跌, 6-爆跌
	PriceChange       field.Float64 // 涨跌幅度
	PriceRange        field.Float64 // 涨跌振幅
	PriceRangePrecent field.Float64 // 涨跌振幅比例
	TriggerTime       field.Int64   // 触发时间

	fieldMap map[string]field.Expr
}

func (b barData1h) Table(newTableName string) *barData1h {
	b.barData1hDo.UseTable(newTableName)
	return b.updateTableName(newTableName)
}

func (b barData1h) As(alias string) *barData1h {
	b.barData1hDo.DO = *(b.barData1hDo.As(alias).(*gen.DO))
	return b.updateTableName(alias)
}

func (b *barData1h) updateTableName(table string) *barData1h {
	b.ALL = field.NewAsterisk(table)
	b.ID = field.NewInt64(table, "id")
	b.CurrencyID = field.NewString(table, "currency_id")
	b.BeginTime = field.NewInt64(table, "begin_time")
	b.OpenPrice = field.NewFloat64(table, "open_price")
	b.ClosePrice = field.NewFloat64(table, "close_price")
	b.HighPrice = field.NewFloat64(table, "high_price")
	b.LowPrice = field.NewFloat64(table, "low_price")
	b.BarType = field.NewString(table, "bar_type")
	b.SigType = field.NewInt64(table, "sig_type")
	b.PriceChange = field.NewFloat64(table, "price_change")
	b.PriceRange = field.NewFloat64(table, "price_range")
	b.PriceRangePrecent = field.NewFloat64(table, "price_range_precent")
	b.TriggerTime = field.NewInt64(table, "trigger_time")

	b.fillFieldMap()

	return b
}

func (b *barData1h) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := b.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (b *barData1h) fillFieldMap() {
	b.fieldMap = make(map[string]field.Expr, 13)
	b.fieldMap["id"] = b.ID
	b.fieldMap["currency_id"] = b.CurrencyID
	b.fieldMap["begin_time"] = b.BeginTime
	b.fieldMap["open_price"] = b.OpenPrice
	b.fieldMap["close_price"] = b.ClosePrice
	b.fieldMap["high_price"] = b.HighPrice
	b.fieldMap["low_price"] = b.LowPrice
	b.fieldMap["bar_type"] = b.BarType
	b.fieldMap["sig_type"] = b.SigType
	b.fieldMap["price_change"] = b.PriceChange
	b.fieldMap["price_range"] = b.PriceRange
	b.fieldMap["price_range_precent"] = b.PriceRangePrecent
	b.fieldMap["trigger_time"] = b.TriggerTime
}

func (b barData1h) clone(db *gorm.DB) barData1h {
	b.barData1hDo.ReplaceConnPool(db.Statement.ConnPool)
	return b
}

func (b barData1h) replaceDB(db *gorm.DB) barData1h {
	b.barData1hDo.ReplaceDB(db)
	return b
}

type barData1hDo struct{ gen.DO }

type IBarData1hDo interface {
	gen.SubQuery
	Debug() IBarData1hDo
	WithContext(ctx context.Context) IBarData1hDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IBarData1hDo
	WriteDB() IBarData1hDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IBarData1hDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IBarData1hDo
	Not(conds ...gen.Condition) IBarData1hDo
	Or(conds ...gen.Condition) IBarData1hDo
	Select(conds ...field.Expr) IBarData1hDo
	Where(conds ...gen.Condition) IBarData1hDo
	Order(conds ...field.Expr) IBarData1hDo
	Distinct(cols ...field.Expr) IBarData1hDo
	Omit(cols ...field.Expr) IBarData1hDo
	Join(table schema.Tabler, on ...field.Expr) IBarData1hDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IBarData1hDo
	RightJoin(table schema.Tabler, on ...field.Expr) IBarData1hDo
	Group(cols ...field.Expr) IBarData1hDo
	Having(conds ...gen.Condition) IBarData1hDo
	Limit(limit int) IBarData1hDo
	Offset(offset int) IBarData1hDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IBarData1hDo
	Unscoped() IBarData1hDo
	Create(values ...*model.BarData1h) error
	CreateInBatches(values []*model.BarData1h, batchSize int) error
	Save(values ...*model.BarData1h) error
	First() (*model.BarData1h, error)
	Take() (*model.BarData1h, error)
	Last() (*model.BarData1h, error)
	Find() ([]*model.BarData1h, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BarData1h, err error)
	FindInBatches(result *[]*model.BarData1h, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.BarData1h) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IBarData1hDo
	Assign(attrs ...field.AssignExpr) IBarData1hDo
	Joins(fields ...field.RelationField) IBarData1hDo
	Preload(fields ...field.RelationField) IBarData1hDo
	FirstOrInit() (*model.BarData1h, error)
	FirstOrCreate() (*model.BarData1h, error)
	FindByPage(offset int, limit int) (result []*model.BarData1h, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IBarData1hDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (b barData1hDo) Debug() IBarData1hDo {
	return b.withDO(b.DO.Debug())
}

func (b barData1hDo) WithContext(ctx context.Context) IBarData1hDo {
	return b.withDO(b.DO.WithContext(ctx))
}

func (b barData1hDo) ReadDB() IBarData1hDo {
	return b.Clauses(dbresolver.Read)
}

func (b barData1hDo) WriteDB() IBarData1hDo {
	return b.Clauses(dbresolver.Write)
}

func (b barData1hDo) Session(config *gorm.Session) IBarData1hDo {
	return b.withDO(b.DO.Session(config))
}

func (b barData1hDo) Clauses(conds ...clause.Expression) IBarData1hDo {
	return b.withDO(b.DO.Clauses(conds...))
}

func (b barData1hDo) Returning(value interface{}, columns ...string) IBarData1hDo {
	return b.withDO(b.DO.Returning(value, columns...))
}

func (b barData1hDo) Not(conds ...gen.Condition) IBarData1hDo {
	return b.withDO(b.DO.Not(conds...))
}

func (b barData1hDo) Or(conds ...gen.Condition) IBarData1hDo {
	return b.withDO(b.DO.Or(conds...))
}

func (b barData1hDo) Select(conds ...field.Expr) IBarData1hDo {
	return b.withDO(b.DO.Select(conds...))
}

func (b barData1hDo) Where(conds ...gen.Condition) IBarData1hDo {
	return b.withDO(b.DO.Where(conds...))
}

func (b barData1hDo) Order(conds ...field.Expr) IBarData1hDo {
	return b.withDO(b.DO.Order(conds...))
}

func (b barData1hDo) Distinct(cols ...field.Expr) IBarData1hDo {
	return b.withDO(b.DO.Distinct(cols...))
}

func (b barData1hDo) Omit(cols ...field.Expr) IBarData1hDo {
	return b.withDO(b.DO.Omit(cols...))
}

func (b barData1hDo) Join(table schema.Tabler, on ...field.Expr) IBarData1hDo {
	return b.withDO(b.DO.Join(table, on...))
}

func (b barData1hDo) LeftJoin(table schema.Tabler, on ...field.Expr) IBarData1hDo {
	return b.withDO(b.DO.LeftJoin(table, on...))
}

func (b barData1hDo) RightJoin(table schema.Tabler, on ...field.Expr) IBarData1hDo {
	return b.withDO(b.DO.RightJoin(table, on...))
}

func (b barData1hDo) Group(cols ...field.Expr) IBarData1hDo {
	return b.withDO(b.DO.Group(cols...))
}

func (b barData1hDo) Having(conds ...gen.Condition) IBarData1hDo {
	return b.withDO(b.DO.Having(conds...))
}

func (b barData1hDo) Limit(limit int) IBarData1hDo {
	return b.withDO(b.DO.Limit(limit))
}

func (b barData1hDo) Offset(offset int) IBarData1hDo {
	return b.withDO(b.DO.Offset(offset))
}

func (b barData1hDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IBarData1hDo {
	return b.withDO(b.DO.Scopes(funcs...))
}

func (b barData1hDo) Unscoped() IBarData1hDo {
	return b.withDO(b.DO.Unscoped())
}

func (b barData1hDo) Create(values ...*model.BarData1h) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Create(values)
}

func (b barData1hDo) CreateInBatches(values []*model.BarData1h, batchSize int) error {
	return b.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (b barData1hDo) Save(values ...*model.BarData1h) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Save(values)
}

func (b barData1hDo) First() (*model.BarData1h, error) {
	if result, err := b.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.BarData1h), nil
	}
}

func (b barData1hDo) Take() (*model.BarData1h, error) {
	if result, err := b.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.BarData1h), nil
	}
}

func (b barData1hDo) Last() (*model.BarData1h, error) {
	if result, err := b.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.BarData1h), nil
	}
}

func (b barData1hDo) Find() ([]*model.BarData1h, error) {
	result, err := b.DO.Find()
	return result.([]*model.BarData1h), err
}

func (b barData1hDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BarData1h, err error) {
	buf := make([]*model.BarData1h, 0, batchSize)
	err = b.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (b barData1hDo) FindInBatches(result *[]*model.BarData1h, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return b.DO.FindInBatches(result, batchSize, fc)
}

func (b barData1hDo) Attrs(attrs ...field.AssignExpr) IBarData1hDo {
	return b.withDO(b.DO.Attrs(attrs...))
}

func (b barData1hDo) Assign(attrs ...field.AssignExpr) IBarData1hDo {
	return b.withDO(b.DO.Assign(attrs...))
}

func (b barData1hDo) Joins(fields ...field.RelationField) IBarData1hDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Joins(_f))
	}
	return &b
}

func (b barData1hDo) Preload(fields ...field.RelationField) IBarData1hDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Preload(_f))
	}
	return &b
}

func (b barData1hDo) FirstOrInit() (*model.BarData1h, error) {
	if result, err := b.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.BarData1h), nil
	}
}

func (b barData1hDo) FirstOrCreate() (*model.BarData1h, error) {
	if result, err := b.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.BarData1h), nil
	}
}

func (b barData1hDo) FindByPage(offset int, limit int) (result []*model.BarData1h, count int64, err error) {
	result, err = b.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = b.Offset(-1).Limit(-1).Count()
	return
}

func (b barData1hDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = b.Count()
	if err != nil {
		return
	}

	err = b.Offset(offset).Limit(limit).Scan(result)
	return
}

func (b barData1hDo) Scan(result interface{}) (err error) {
	return b.DO.Scan(result)
}

func (b barData1hDo) Delete(models ...*model.BarData1h) (result gen.ResultInfo, err error) {
	return b.DO.Delete(models)
}

func (b *barData1hDo) withDO(do gen.Dao) *barData1hDo {
	b.DO = *do.(*gen.DO)
	return b
}
