// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/ocean386/common/orm/model"
)

func newBarDataDay(db *gorm.DB, opts ...gen.DOOption) barDataDay {
	_barDataDay := barDataDay{}

	_barDataDay.barDataDayDo.UseDB(db, opts...)
	_barDataDay.barDataDayDo.UseModel(&model.BarDataDay{})

	tableName := _barDataDay.barDataDayDo.TableName()
	_barDataDay.ALL = field.NewAsterisk(tableName)
	_barDataDay.ID = field.NewInt64(tableName, "id")
	_barDataDay.CurrencyID = field.NewString(tableName, "currency_id")
	_barDataDay.BeginTime = field.NewInt64(tableName, "begin_time")
	_barDataDay.OpenPrice = field.NewFloat64(tableName, "open_price")
	_barDataDay.ClosePrice = field.NewFloat64(tableName, "close_price")
	_barDataDay.HighPrice = field.NewFloat64(tableName, "high_price")
	_barDataDay.LowPrice = field.NewFloat64(tableName, "low_price")
	_barDataDay.BarType = field.NewString(tableName, "bar_type")
	_barDataDay.SigType = field.NewInt64(tableName, "sig_type")
	_barDataDay.PriceChange = field.NewFloat64(tableName, "price_change")
	_barDataDay.PriceRange = field.NewFloat64(tableName, "price_range")
	_barDataDay.PriceRangePrecent = field.NewFloat64(tableName, "price_range_precent")
	_barDataDay.TriggerTime = field.NewInt64(tableName, "trigger_time")

	_barDataDay.fillFieldMap()

	return _barDataDay
}

// barDataDay 时间粒度表-每日
type barDataDay struct {
	barDataDayDo

	ALL               field.Asterisk
	ID                field.Int64   // 主键ID
	CurrencyID        field.String  // 币种ID
	BeginTime         field.Int64   // 开始时间
	OpenPrice         field.Float64 // 开盘价格
	ClosePrice        field.Float64 // 收盘价格
	HighPrice         field.Float64 // 最高价格
	LowPrice          field.Float64 // 最低价格
	BarType           field.String  // 时间粒度类型:默认值1m,1m/5m/15m/30m/1H/4H/12H/1D/1W/1M
	SigType           field.Int64   // 行情信号: 0-/, 1-上涨, 2-快速上涨, 3-爆涨, 4-下跌, 5-快速下跌, 6-爆跌
	PriceChange       field.Float64 // 涨跌幅度
	PriceRange        field.Float64 // 涨跌振幅
	PriceRangePrecent field.Float64 // 涨跌振幅比例
	TriggerTime       field.Int64   // 触发时间

	fieldMap map[string]field.Expr
}

func (b barDataDay) Table(newTableName string) *barDataDay {
	b.barDataDayDo.UseTable(newTableName)
	return b.updateTableName(newTableName)
}

func (b barDataDay) As(alias string) *barDataDay {
	b.barDataDayDo.DO = *(b.barDataDayDo.As(alias).(*gen.DO))
	return b.updateTableName(alias)
}

func (b *barDataDay) updateTableName(table string) *barDataDay {
	b.ALL = field.NewAsterisk(table)
	b.ID = field.NewInt64(table, "id")
	b.CurrencyID = field.NewString(table, "currency_id")
	b.BeginTime = field.NewInt64(table, "begin_time")
	b.OpenPrice = field.NewFloat64(table, "open_price")
	b.ClosePrice = field.NewFloat64(table, "close_price")
	b.HighPrice = field.NewFloat64(table, "high_price")
	b.LowPrice = field.NewFloat64(table, "low_price")
	b.BarType = field.NewString(table, "bar_type")
	b.SigType = field.NewInt64(table, "sig_type")
	b.PriceChange = field.NewFloat64(table, "price_change")
	b.PriceRange = field.NewFloat64(table, "price_range")
	b.PriceRangePrecent = field.NewFloat64(table, "price_range_precent")
	b.TriggerTime = field.NewInt64(table, "trigger_time")

	b.fillFieldMap()

	return b
}

func (b *barDataDay) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := b.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (b *barDataDay) fillFieldMap() {
	b.fieldMap = make(map[string]field.Expr, 13)
	b.fieldMap["id"] = b.ID
	b.fieldMap["currency_id"] = b.CurrencyID
	b.fieldMap["begin_time"] = b.BeginTime
	b.fieldMap["open_price"] = b.OpenPrice
	b.fieldMap["close_price"] = b.ClosePrice
	b.fieldMap["high_price"] = b.HighPrice
	b.fieldMap["low_price"] = b.LowPrice
	b.fieldMap["bar_type"] = b.BarType
	b.fieldMap["sig_type"] = b.SigType
	b.fieldMap["price_change"] = b.PriceChange
	b.fieldMap["price_range"] = b.PriceRange
	b.fieldMap["price_range_precent"] = b.PriceRangePrecent
	b.fieldMap["trigger_time"] = b.TriggerTime
}

func (b barDataDay) clone(db *gorm.DB) barDataDay {
	b.barDataDayDo.ReplaceConnPool(db.Statement.ConnPool)
	return b
}

func (b barDataDay) replaceDB(db *gorm.DB) barDataDay {
	b.barDataDayDo.ReplaceDB(db)
	return b
}

type barDataDayDo struct{ gen.DO }

type IBarDataDayDo interface {
	gen.SubQuery
	Debug() IBarDataDayDo
	WithContext(ctx context.Context) IBarDataDayDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IBarDataDayDo
	WriteDB() IBarDataDayDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IBarDataDayDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IBarDataDayDo
	Not(conds ...gen.Condition) IBarDataDayDo
	Or(conds ...gen.Condition) IBarDataDayDo
	Select(conds ...field.Expr) IBarDataDayDo
	Where(conds ...gen.Condition) IBarDataDayDo
	Order(conds ...field.Expr) IBarDataDayDo
	Distinct(cols ...field.Expr) IBarDataDayDo
	Omit(cols ...field.Expr) IBarDataDayDo
	Join(table schema.Tabler, on ...field.Expr) IBarDataDayDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IBarDataDayDo
	RightJoin(table schema.Tabler, on ...field.Expr) IBarDataDayDo
	Group(cols ...field.Expr) IBarDataDayDo
	Having(conds ...gen.Condition) IBarDataDayDo
	Limit(limit int) IBarDataDayDo
	Offset(offset int) IBarDataDayDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IBarDataDayDo
	Unscoped() IBarDataDayDo
	Create(values ...*model.BarDataDay) error
	CreateInBatches(values []*model.BarDataDay, batchSize int) error
	Save(values ...*model.BarDataDay) error
	First() (*model.BarDataDay, error)
	Take() (*model.BarDataDay, error)
	Last() (*model.BarDataDay, error)
	Find() ([]*model.BarDataDay, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BarDataDay, err error)
	FindInBatches(result *[]*model.BarDataDay, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.BarDataDay) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IBarDataDayDo
	Assign(attrs ...field.AssignExpr) IBarDataDayDo
	Joins(fields ...field.RelationField) IBarDataDayDo
	Preload(fields ...field.RelationField) IBarDataDayDo
	FirstOrInit() (*model.BarDataDay, error)
	FirstOrCreate() (*model.BarDataDay, error)
	FindByPage(offset int, limit int) (result []*model.BarDataDay, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IBarDataDayDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (b barDataDayDo) Debug() IBarDataDayDo {
	return b.withDO(b.DO.Debug())
}

func (b barDataDayDo) WithContext(ctx context.Context) IBarDataDayDo {
	return b.withDO(b.DO.WithContext(ctx))
}

func (b barDataDayDo) ReadDB() IBarDataDayDo {
	return b.Clauses(dbresolver.Read)
}

func (b barDataDayDo) WriteDB() IBarDataDayDo {
	return b.Clauses(dbresolver.Write)
}

func (b barDataDayDo) Session(config *gorm.Session) IBarDataDayDo {
	return b.withDO(b.DO.Session(config))
}

func (b barDataDayDo) Clauses(conds ...clause.Expression) IBarDataDayDo {
	return b.withDO(b.DO.Clauses(conds...))
}

func (b barDataDayDo) Returning(value interface{}, columns ...string) IBarDataDayDo {
	return b.withDO(b.DO.Returning(value, columns...))
}

func (b barDataDayDo) Not(conds ...gen.Condition) IBarDataDayDo {
	return b.withDO(b.DO.Not(conds...))
}

func (b barDataDayDo) Or(conds ...gen.Condition) IBarDataDayDo {
	return b.withDO(b.DO.Or(conds...))
}

func (b barDataDayDo) Select(conds ...field.Expr) IBarDataDayDo {
	return b.withDO(b.DO.Select(conds...))
}

func (b barDataDayDo) Where(conds ...gen.Condition) IBarDataDayDo {
	return b.withDO(b.DO.Where(conds...))
}

func (b barDataDayDo) Order(conds ...field.Expr) IBarDataDayDo {
	return b.withDO(b.DO.Order(conds...))
}

func (b barDataDayDo) Distinct(cols ...field.Expr) IBarDataDayDo {
	return b.withDO(b.DO.Distinct(cols...))
}

func (b barDataDayDo) Omit(cols ...field.Expr) IBarDataDayDo {
	return b.withDO(b.DO.Omit(cols...))
}

func (b barDataDayDo) Join(table schema.Tabler, on ...field.Expr) IBarDataDayDo {
	return b.withDO(b.DO.Join(table, on...))
}

func (b barDataDayDo) LeftJoin(table schema.Tabler, on ...field.Expr) IBarDataDayDo {
	return b.withDO(b.DO.LeftJoin(table, on...))
}

func (b barDataDayDo) RightJoin(table schema.Tabler, on ...field.Expr) IBarDataDayDo {
	return b.withDO(b.DO.RightJoin(table, on...))
}

func (b barDataDayDo) Group(cols ...field.Expr) IBarDataDayDo {
	return b.withDO(b.DO.Group(cols...))
}

func (b barDataDayDo) Having(conds ...gen.Condition) IBarDataDayDo {
	return b.withDO(b.DO.Having(conds...))
}

func (b barDataDayDo) Limit(limit int) IBarDataDayDo {
	return b.withDO(b.DO.Limit(limit))
}

func (b barDataDayDo) Offset(offset int) IBarDataDayDo {
	return b.withDO(b.DO.Offset(offset))
}

func (b barDataDayDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IBarDataDayDo {
	return b.withDO(b.DO.Scopes(funcs...))
}

func (b barDataDayDo) Unscoped() IBarDataDayDo {
	return b.withDO(b.DO.Unscoped())
}

func (b barDataDayDo) Create(values ...*model.BarDataDay) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Create(values)
}

func (b barDataDayDo) CreateInBatches(values []*model.BarDataDay, batchSize int) error {
	return b.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (b barDataDayDo) Save(values ...*model.BarDataDay) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Save(values)
}

func (b barDataDayDo) First() (*model.BarDataDay, error) {
	if result, err := b.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.BarDataDay), nil
	}
}

func (b barDataDayDo) Take() (*model.BarDataDay, error) {
	if result, err := b.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.BarDataDay), nil
	}
}

func (b barDataDayDo) Last() (*model.BarDataDay, error) {
	if result, err := b.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.BarDataDay), nil
	}
}

func (b barDataDayDo) Find() ([]*model.BarDataDay, error) {
	result, err := b.DO.Find()
	return result.([]*model.BarDataDay), err
}

func (b barDataDayDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BarDataDay, err error) {
	buf := make([]*model.BarDataDay, 0, batchSize)
	err = b.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (b barDataDayDo) FindInBatches(result *[]*model.BarDataDay, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return b.DO.FindInBatches(result, batchSize, fc)
}

func (b barDataDayDo) Attrs(attrs ...field.AssignExpr) IBarDataDayDo {
	return b.withDO(b.DO.Attrs(attrs...))
}

func (b barDataDayDo) Assign(attrs ...field.AssignExpr) IBarDataDayDo {
	return b.withDO(b.DO.Assign(attrs...))
}

func (b barDataDayDo) Joins(fields ...field.RelationField) IBarDataDayDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Joins(_f))
	}
	return &b
}

func (b barDataDayDo) Preload(fields ...field.RelationField) IBarDataDayDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Preload(_f))
	}
	return &b
}

func (b barDataDayDo) FirstOrInit() (*model.BarDataDay, error) {
	if result, err := b.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.BarDataDay), nil
	}
}

func (b barDataDayDo) FirstOrCreate() (*model.BarDataDay, error) {
	if result, err := b.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.BarDataDay), nil
	}
}

func (b barDataDayDo) FindByPage(offset int, limit int) (result []*model.BarDataDay, count int64, err error) {
	result, err = b.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = b.Offset(-1).Limit(-1).Count()
	return
}

func (b barDataDayDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = b.Count()
	if err != nil {
		return
	}

	err = b.Offset(offset).Limit(limit).Scan(result)
	return
}

func (b barDataDayDo) Scan(result interface{}) (err error) {
	return b.DO.Scan(result)
}

func (b barDataDayDo) Delete(models ...*model.BarDataDay) (result gen.ResultInfo, err error) {
	return b.DO.Delete(models)
}

func (b *barDataDayDo) withDO(do gen.Dao) *barDataDayDo {
	b.DO = *do.(*gen.DO)
	return b
}
