// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/ocean386/common/orm/model"
)

func newBarDataMonth(db *gorm.DB, opts ...gen.DOOption) barDataMonth {
	_barDataMonth := barDataMonth{}

	_barDataMonth.barDataMonthDo.UseDB(db, opts...)
	_barDataMonth.barDataMonthDo.UseModel(&model.BarDataMonth{})

	tableName := _barDataMonth.barDataMonthDo.TableName()
	_barDataMonth.ALL = field.NewAsterisk(tableName)
	_barDataMonth.ID = field.NewInt64(tableName, "id")
	_barDataMonth.CurrencyID = field.NewString(tableName, "currency_id")
	_barDataMonth.BeginTime = field.NewInt64(tableName, "begin_time")
	_barDataMonth.OpenPrice = field.NewFloat64(tableName, "open_price")
	_barDataMonth.ClosePrice = field.NewFloat64(tableName, "close_price")
	_barDataMonth.HighPrice = field.NewFloat64(tableName, "high_price")
	_barDataMonth.LowPrice = field.NewFloat64(tableName, "low_price")
	_barDataMonth.BarType = field.NewString(tableName, "bar_type")
	_barDataMonth.SigType = field.NewInt64(tableName, "sig_type")
	_barDataMonth.PriceChange = field.NewFloat64(tableName, "price_change")
	_barDataMonth.PriceRange = field.NewFloat64(tableName, "price_range")
	_barDataMonth.PriceRangePrecent = field.NewFloat64(tableName, "price_range_precent")
	_barDataMonth.TriggerTime = field.NewInt64(tableName, "trigger_time")

	_barDataMonth.fillFieldMap()

	return _barDataMonth
}

// barDataMonth 时间粒度表-每月
type barDataMonth struct {
	barDataMonthDo

	ALL               field.Asterisk
	ID                field.Int64   // 主键ID
	CurrencyID        field.String  // 币种ID
	BeginTime         field.Int64   // 开始时间
	OpenPrice         field.Float64 // 开盘价格
	ClosePrice        field.Float64 // 收盘价格
	HighPrice         field.Float64 // 最高价格
	LowPrice          field.Float64 // 最低价格
	BarType           field.String  // 时间粒度类型:默认值1m,1m/5m/15m/30m/1H/4H/12H/1D/1W/1M
	SigType           field.Int64   // 行情信号: 0-/, 1-上涨, 2-快速上涨, 3-爆涨, 4-下跌, 5-快速下跌, 6-爆跌
	PriceChange       field.Float64 // 涨跌幅度
	PriceRange        field.Float64 // 涨跌振幅
	PriceRangePrecent field.Float64 // 涨跌振幅比例
	TriggerTime       field.Int64   // 触发时间

	fieldMap map[string]field.Expr
}

func (b barDataMonth) Table(newTableName string) *barDataMonth {
	b.barDataMonthDo.UseTable(newTableName)
	return b.updateTableName(newTableName)
}

func (b barDataMonth) As(alias string) *barDataMonth {
	b.barDataMonthDo.DO = *(b.barDataMonthDo.As(alias).(*gen.DO))
	return b.updateTableName(alias)
}

func (b *barDataMonth) updateTableName(table string) *barDataMonth {
	b.ALL = field.NewAsterisk(table)
	b.ID = field.NewInt64(table, "id")
	b.CurrencyID = field.NewString(table, "currency_id")
	b.BeginTime = field.NewInt64(table, "begin_time")
	b.OpenPrice = field.NewFloat64(table, "open_price")
	b.ClosePrice = field.NewFloat64(table, "close_price")
	b.HighPrice = field.NewFloat64(table, "high_price")
	b.LowPrice = field.NewFloat64(table, "low_price")
	b.BarType = field.NewString(table, "bar_type")
	b.SigType = field.NewInt64(table, "sig_type")
	b.PriceChange = field.NewFloat64(table, "price_change")
	b.PriceRange = field.NewFloat64(table, "price_range")
	b.PriceRangePrecent = field.NewFloat64(table, "price_range_precent")
	b.TriggerTime = field.NewInt64(table, "trigger_time")

	b.fillFieldMap()

	return b
}

func (b *barDataMonth) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := b.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (b *barDataMonth) fillFieldMap() {
	b.fieldMap = make(map[string]field.Expr, 13)
	b.fieldMap["id"] = b.ID
	b.fieldMap["currency_id"] = b.CurrencyID
	b.fieldMap["begin_time"] = b.BeginTime
	b.fieldMap["open_price"] = b.OpenPrice
	b.fieldMap["close_price"] = b.ClosePrice
	b.fieldMap["high_price"] = b.HighPrice
	b.fieldMap["low_price"] = b.LowPrice
	b.fieldMap["bar_type"] = b.BarType
	b.fieldMap["sig_type"] = b.SigType
	b.fieldMap["price_change"] = b.PriceChange
	b.fieldMap["price_range"] = b.PriceRange
	b.fieldMap["price_range_precent"] = b.PriceRangePrecent
	b.fieldMap["trigger_time"] = b.TriggerTime
}

func (b barDataMonth) clone(db *gorm.DB) barDataMonth {
	b.barDataMonthDo.ReplaceConnPool(db.Statement.ConnPool)
	return b
}

func (b barDataMonth) replaceDB(db *gorm.DB) barDataMonth {
	b.barDataMonthDo.ReplaceDB(db)
	return b
}

type barDataMonthDo struct{ gen.DO }

type IBarDataMonthDo interface {
	gen.SubQuery
	Debug() IBarDataMonthDo
	WithContext(ctx context.Context) IBarDataMonthDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IBarDataMonthDo
	WriteDB() IBarDataMonthDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IBarDataMonthDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IBarDataMonthDo
	Not(conds ...gen.Condition) IBarDataMonthDo
	Or(conds ...gen.Condition) IBarDataMonthDo
	Select(conds ...field.Expr) IBarDataMonthDo
	Where(conds ...gen.Condition) IBarDataMonthDo
	Order(conds ...field.Expr) IBarDataMonthDo
	Distinct(cols ...field.Expr) IBarDataMonthDo
	Omit(cols ...field.Expr) IBarDataMonthDo
	Join(table schema.Tabler, on ...field.Expr) IBarDataMonthDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IBarDataMonthDo
	RightJoin(table schema.Tabler, on ...field.Expr) IBarDataMonthDo
	Group(cols ...field.Expr) IBarDataMonthDo
	Having(conds ...gen.Condition) IBarDataMonthDo
	Limit(limit int) IBarDataMonthDo
	Offset(offset int) IBarDataMonthDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IBarDataMonthDo
	Unscoped() IBarDataMonthDo
	Create(values ...*model.BarDataMonth) error
	CreateInBatches(values []*model.BarDataMonth, batchSize int) error
	Save(values ...*model.BarDataMonth) error
	First() (*model.BarDataMonth, error)
	Take() (*model.BarDataMonth, error)
	Last() (*model.BarDataMonth, error)
	Find() ([]*model.BarDataMonth, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BarDataMonth, err error)
	FindInBatches(result *[]*model.BarDataMonth, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.BarDataMonth) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IBarDataMonthDo
	Assign(attrs ...field.AssignExpr) IBarDataMonthDo
	Joins(fields ...field.RelationField) IBarDataMonthDo
	Preload(fields ...field.RelationField) IBarDataMonthDo
	FirstOrInit() (*model.BarDataMonth, error)
	FirstOrCreate() (*model.BarDataMonth, error)
	FindByPage(offset int, limit int) (result []*model.BarDataMonth, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IBarDataMonthDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (b barDataMonthDo) Debug() IBarDataMonthDo {
	return b.withDO(b.DO.Debug())
}

func (b barDataMonthDo) WithContext(ctx context.Context) IBarDataMonthDo {
	return b.withDO(b.DO.WithContext(ctx))
}

func (b barDataMonthDo) ReadDB() IBarDataMonthDo {
	return b.Clauses(dbresolver.Read)
}

func (b barDataMonthDo) WriteDB() IBarDataMonthDo {
	return b.Clauses(dbresolver.Write)
}

func (b barDataMonthDo) Session(config *gorm.Session) IBarDataMonthDo {
	return b.withDO(b.DO.Session(config))
}

func (b barDataMonthDo) Clauses(conds ...clause.Expression) IBarDataMonthDo {
	return b.withDO(b.DO.Clauses(conds...))
}

func (b barDataMonthDo) Returning(value interface{}, columns ...string) IBarDataMonthDo {
	return b.withDO(b.DO.Returning(value, columns...))
}

func (b barDataMonthDo) Not(conds ...gen.Condition) IBarDataMonthDo {
	return b.withDO(b.DO.Not(conds...))
}

func (b barDataMonthDo) Or(conds ...gen.Condition) IBarDataMonthDo {
	return b.withDO(b.DO.Or(conds...))
}

func (b barDataMonthDo) Select(conds ...field.Expr) IBarDataMonthDo {
	return b.withDO(b.DO.Select(conds...))
}

func (b barDataMonthDo) Where(conds ...gen.Condition) IBarDataMonthDo {
	return b.withDO(b.DO.Where(conds...))
}

func (b barDataMonthDo) Order(conds ...field.Expr) IBarDataMonthDo {
	return b.withDO(b.DO.Order(conds...))
}

func (b barDataMonthDo) Distinct(cols ...field.Expr) IBarDataMonthDo {
	return b.withDO(b.DO.Distinct(cols...))
}

func (b barDataMonthDo) Omit(cols ...field.Expr) IBarDataMonthDo {
	return b.withDO(b.DO.Omit(cols...))
}

func (b barDataMonthDo) Join(table schema.Tabler, on ...field.Expr) IBarDataMonthDo {
	return b.withDO(b.DO.Join(table, on...))
}

func (b barDataMonthDo) LeftJoin(table schema.Tabler, on ...field.Expr) IBarDataMonthDo {
	return b.withDO(b.DO.LeftJoin(table, on...))
}

func (b barDataMonthDo) RightJoin(table schema.Tabler, on ...field.Expr) IBarDataMonthDo {
	return b.withDO(b.DO.RightJoin(table, on...))
}

func (b barDataMonthDo) Group(cols ...field.Expr) IBarDataMonthDo {
	return b.withDO(b.DO.Group(cols...))
}

func (b barDataMonthDo) Having(conds ...gen.Condition) IBarDataMonthDo {
	return b.withDO(b.DO.Having(conds...))
}

func (b barDataMonthDo) Limit(limit int) IBarDataMonthDo {
	return b.withDO(b.DO.Limit(limit))
}

func (b barDataMonthDo) Offset(offset int) IBarDataMonthDo {
	return b.withDO(b.DO.Offset(offset))
}

func (b barDataMonthDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IBarDataMonthDo {
	return b.withDO(b.DO.Scopes(funcs...))
}

func (b barDataMonthDo) Unscoped() IBarDataMonthDo {
	return b.withDO(b.DO.Unscoped())
}

func (b barDataMonthDo) Create(values ...*model.BarDataMonth) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Create(values)
}

func (b barDataMonthDo) CreateInBatches(values []*model.BarDataMonth, batchSize int) error {
	return b.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (b barDataMonthDo) Save(values ...*model.BarDataMonth) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Save(values)
}

func (b barDataMonthDo) First() (*model.BarDataMonth, error) {
	if result, err := b.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.BarDataMonth), nil
	}
}

func (b barDataMonthDo) Take() (*model.BarDataMonth, error) {
	if result, err := b.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.BarDataMonth), nil
	}
}

func (b barDataMonthDo) Last() (*model.BarDataMonth, error) {
	if result, err := b.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.BarDataMonth), nil
	}
}

func (b barDataMonthDo) Find() ([]*model.BarDataMonth, error) {
	result, err := b.DO.Find()
	return result.([]*model.BarDataMonth), err
}

func (b barDataMonthDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BarDataMonth, err error) {
	buf := make([]*model.BarDataMonth, 0, batchSize)
	err = b.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (b barDataMonthDo) FindInBatches(result *[]*model.BarDataMonth, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return b.DO.FindInBatches(result, batchSize, fc)
}

func (b barDataMonthDo) Attrs(attrs ...field.AssignExpr) IBarDataMonthDo {
	return b.withDO(b.DO.Attrs(attrs...))
}

func (b barDataMonthDo) Assign(attrs ...field.AssignExpr) IBarDataMonthDo {
	return b.withDO(b.DO.Assign(attrs...))
}

func (b barDataMonthDo) Joins(fields ...field.RelationField) IBarDataMonthDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Joins(_f))
	}
	return &b
}

func (b barDataMonthDo) Preload(fields ...field.RelationField) IBarDataMonthDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Preload(_f))
	}
	return &b
}

func (b barDataMonthDo) FirstOrInit() (*model.BarDataMonth, error) {
	if result, err := b.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.BarDataMonth), nil
	}
}

func (b barDataMonthDo) FirstOrCreate() (*model.BarDataMonth, error) {
	if result, err := b.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.BarDataMonth), nil
	}
}

func (b barDataMonthDo) FindByPage(offset int, limit int) (result []*model.BarDataMonth, count int64, err error) {
	result, err = b.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = b.Offset(-1).Limit(-1).Count()
	return
}

func (b barDataMonthDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = b.Count()
	if err != nil {
		return
	}

	err = b.Offset(offset).Limit(limit).Scan(result)
	return
}

func (b barDataMonthDo) Scan(result interface{}) (err error) {
	return b.DO.Scan(result)
}

func (b barDataMonthDo) Delete(models ...*model.BarDataMonth) (result gen.ResultInfo, err error) {
	return b.DO.Delete(models)
}

func (b *barDataMonthDo) withDO(do gen.Dao) *barDataMonthDo {
	b.DO = *do.(*gen.DO)
	return b
}
