// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/ocean386/common/orm/model"
)

func newBarData12h(db *gorm.DB, opts ...gen.DOOption) barData12h {
	_barData12h := barData12h{}

	_barData12h.barData12hDo.UseDB(db, opts...)
	_barData12h.barData12hDo.UseModel(&model.BarData12h{})

	tableName := _barData12h.barData12hDo.TableName()
	_barData12h.ALL = field.NewAsterisk(tableName)
	_barData12h.ID = field.NewInt64(tableName, "id")
	_barData12h.CurrencyID = field.NewString(tableName, "currency_id")
	_barData12h.BeginTime = field.NewInt64(tableName, "begin_time")
	_barData12h.OpenPrice = field.NewFloat64(tableName, "open_price")
	_barData12h.ClosePrice = field.NewFloat64(tableName, "close_price")
	_barData12h.HighPrice = field.NewFloat64(tableName, "high_price")
	_barData12h.LowPrice = field.NewFloat64(tableName, "low_price")
	_barData12h.BarType = field.NewString(tableName, "bar_type")
	_barData12h.SigType = field.NewInt64(tableName, "sig_type")
	_barData12h.PriceChange = field.NewFloat64(tableName, "price_change")
	_barData12h.PriceRange = field.NewFloat64(tableName, "price_range")
	_barData12h.PriceRangePrecent = field.NewFloat64(tableName, "price_range_precent")
	_barData12h.TriggerTime = field.NewInt64(tableName, "trigger_time")

	_barData12h.fillFieldMap()

	return _barData12h
}

// barData12h 时间粒度表-每12小时
type barData12h struct {
	barData12hDo

	ALL               field.Asterisk
	ID                field.Int64   // 主键ID
	CurrencyID        field.String  // 币种ID
	BeginTime         field.Int64   // 开始时间
	OpenPrice         field.Float64 // 开盘价格
	ClosePrice        field.Float64 // 收盘价格
	HighPrice         field.Float64 // 最高价格
	LowPrice          field.Float64 // 最低价格
	BarType           field.String  // 时间粒度类型:默认值1m,1m/5m/15m/30m/1H/4H/12H/1D/1W/1M
	SigType           field.Int64   // 行情信号: 0-/, 1-上涨, 2-快速上涨, 3-爆涨, 4-下跌, 5-快速下跌, 6-爆跌
	PriceChange       field.Float64 // 涨跌幅度
	PriceRange        field.Float64 // 涨跌振幅
	PriceRangePrecent field.Float64 // 涨跌振幅比例
	TriggerTime       field.Int64   // 触发时间

	fieldMap map[string]field.Expr
}

func (b barData12h) Table(newTableName string) *barData12h {
	b.barData12hDo.UseTable(newTableName)
	return b.updateTableName(newTableName)
}

func (b barData12h) As(alias string) *barData12h {
	b.barData12hDo.DO = *(b.barData12hDo.As(alias).(*gen.DO))
	return b.updateTableName(alias)
}

func (b *barData12h) updateTableName(table string) *barData12h {
	b.ALL = field.NewAsterisk(table)
	b.ID = field.NewInt64(table, "id")
	b.CurrencyID = field.NewString(table, "currency_id")
	b.BeginTime = field.NewInt64(table, "begin_time")
	b.OpenPrice = field.NewFloat64(table, "open_price")
	b.ClosePrice = field.NewFloat64(table, "close_price")
	b.HighPrice = field.NewFloat64(table, "high_price")
	b.LowPrice = field.NewFloat64(table, "low_price")
	b.BarType = field.NewString(table, "bar_type")
	b.SigType = field.NewInt64(table, "sig_type")
	b.PriceChange = field.NewFloat64(table, "price_change")
	b.PriceRange = field.NewFloat64(table, "price_range")
	b.PriceRangePrecent = field.NewFloat64(table, "price_range_precent")
	b.TriggerTime = field.NewInt64(table, "trigger_time")

	b.fillFieldMap()

	return b
}

func (b *barData12h) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := b.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (b *barData12h) fillFieldMap() {
	b.fieldMap = make(map[string]field.Expr, 13)
	b.fieldMap["id"] = b.ID
	b.fieldMap["currency_id"] = b.CurrencyID
	b.fieldMap["begin_time"] = b.BeginTime
	b.fieldMap["open_price"] = b.OpenPrice
	b.fieldMap["close_price"] = b.ClosePrice
	b.fieldMap["high_price"] = b.HighPrice
	b.fieldMap["low_price"] = b.LowPrice
	b.fieldMap["bar_type"] = b.BarType
	b.fieldMap["sig_type"] = b.SigType
	b.fieldMap["price_change"] = b.PriceChange
	b.fieldMap["price_range"] = b.PriceRange
	b.fieldMap["price_range_precent"] = b.PriceRangePrecent
	b.fieldMap["trigger_time"] = b.TriggerTime
}

func (b barData12h) clone(db *gorm.DB) barData12h {
	b.barData12hDo.ReplaceConnPool(db.Statement.ConnPool)
	return b
}

func (b barData12h) replaceDB(db *gorm.DB) barData12h {
	b.barData12hDo.ReplaceDB(db)
	return b
}

type barData12hDo struct{ gen.DO }

type IBarData12hDo interface {
	gen.SubQuery
	Debug() IBarData12hDo
	WithContext(ctx context.Context) IBarData12hDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IBarData12hDo
	WriteDB() IBarData12hDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IBarData12hDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IBarData12hDo
	Not(conds ...gen.Condition) IBarData12hDo
	Or(conds ...gen.Condition) IBarData12hDo
	Select(conds ...field.Expr) IBarData12hDo
	Where(conds ...gen.Condition) IBarData12hDo
	Order(conds ...field.Expr) IBarData12hDo
	Distinct(cols ...field.Expr) IBarData12hDo
	Omit(cols ...field.Expr) IBarData12hDo
	Join(table schema.Tabler, on ...field.Expr) IBarData12hDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IBarData12hDo
	RightJoin(table schema.Tabler, on ...field.Expr) IBarData12hDo
	Group(cols ...field.Expr) IBarData12hDo
	Having(conds ...gen.Condition) IBarData12hDo
	Limit(limit int) IBarData12hDo
	Offset(offset int) IBarData12hDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IBarData12hDo
	Unscoped() IBarData12hDo
	Create(values ...*model.BarData12h) error
	CreateInBatches(values []*model.BarData12h, batchSize int) error
	Save(values ...*model.BarData12h) error
	First() (*model.BarData12h, error)
	Take() (*model.BarData12h, error)
	Last() (*model.BarData12h, error)
	Find() ([]*model.BarData12h, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BarData12h, err error)
	FindInBatches(result *[]*model.BarData12h, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.BarData12h) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IBarData12hDo
	Assign(attrs ...field.AssignExpr) IBarData12hDo
	Joins(fields ...field.RelationField) IBarData12hDo
	Preload(fields ...field.RelationField) IBarData12hDo
	FirstOrInit() (*model.BarData12h, error)
	FirstOrCreate() (*model.BarData12h, error)
	FindByPage(offset int, limit int) (result []*model.BarData12h, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IBarData12hDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (b barData12hDo) Debug() IBarData12hDo {
	return b.withDO(b.DO.Debug())
}

func (b barData12hDo) WithContext(ctx context.Context) IBarData12hDo {
	return b.withDO(b.DO.WithContext(ctx))
}

func (b barData12hDo) ReadDB() IBarData12hDo {
	return b.Clauses(dbresolver.Read)
}

func (b barData12hDo) WriteDB() IBarData12hDo {
	return b.Clauses(dbresolver.Write)
}

func (b barData12hDo) Session(config *gorm.Session) IBarData12hDo {
	return b.withDO(b.DO.Session(config))
}

func (b barData12hDo) Clauses(conds ...clause.Expression) IBarData12hDo {
	return b.withDO(b.DO.Clauses(conds...))
}

func (b barData12hDo) Returning(value interface{}, columns ...string) IBarData12hDo {
	return b.withDO(b.DO.Returning(value, columns...))
}

func (b barData12hDo) Not(conds ...gen.Condition) IBarData12hDo {
	return b.withDO(b.DO.Not(conds...))
}

func (b barData12hDo) Or(conds ...gen.Condition) IBarData12hDo {
	return b.withDO(b.DO.Or(conds...))
}

func (b barData12hDo) Select(conds ...field.Expr) IBarData12hDo {
	return b.withDO(b.DO.Select(conds...))
}

func (b barData12hDo) Where(conds ...gen.Condition) IBarData12hDo {
	return b.withDO(b.DO.Where(conds...))
}

func (b barData12hDo) Order(conds ...field.Expr) IBarData12hDo {
	return b.withDO(b.DO.Order(conds...))
}

func (b barData12hDo) Distinct(cols ...field.Expr) IBarData12hDo {
	return b.withDO(b.DO.Distinct(cols...))
}

func (b barData12hDo) Omit(cols ...field.Expr) IBarData12hDo {
	return b.withDO(b.DO.Omit(cols...))
}

func (b barData12hDo) Join(table schema.Tabler, on ...field.Expr) IBarData12hDo {
	return b.withDO(b.DO.Join(table, on...))
}

func (b barData12hDo) LeftJoin(table schema.Tabler, on ...field.Expr) IBarData12hDo {
	return b.withDO(b.DO.LeftJoin(table, on...))
}

func (b barData12hDo) RightJoin(table schema.Tabler, on ...field.Expr) IBarData12hDo {
	return b.withDO(b.DO.RightJoin(table, on...))
}

func (b barData12hDo) Group(cols ...field.Expr) IBarData12hDo {
	return b.withDO(b.DO.Group(cols...))
}

func (b barData12hDo) Having(conds ...gen.Condition) IBarData12hDo {
	return b.withDO(b.DO.Having(conds...))
}

func (b barData12hDo) Limit(limit int) IBarData12hDo {
	return b.withDO(b.DO.Limit(limit))
}

func (b barData12hDo) Offset(offset int) IBarData12hDo {
	return b.withDO(b.DO.Offset(offset))
}

func (b barData12hDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IBarData12hDo {
	return b.withDO(b.DO.Scopes(funcs...))
}

func (b barData12hDo) Unscoped() IBarData12hDo {
	return b.withDO(b.DO.Unscoped())
}

func (b barData12hDo) Create(values ...*model.BarData12h) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Create(values)
}

func (b barData12hDo) CreateInBatches(values []*model.BarData12h, batchSize int) error {
	return b.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (b barData12hDo) Save(values ...*model.BarData12h) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Save(values)
}

func (b barData12hDo) First() (*model.BarData12h, error) {
	if result, err := b.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.BarData12h), nil
	}
}

func (b barData12hDo) Take() (*model.BarData12h, error) {
	if result, err := b.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.BarData12h), nil
	}
}

func (b barData12hDo) Last() (*model.BarData12h, error) {
	if result, err := b.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.BarData12h), nil
	}
}

func (b barData12hDo) Find() ([]*model.BarData12h, error) {
	result, err := b.DO.Find()
	return result.([]*model.BarData12h), err
}

func (b barData12hDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BarData12h, err error) {
	buf := make([]*model.BarData12h, 0, batchSize)
	err = b.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (b barData12hDo) FindInBatches(result *[]*model.BarData12h, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return b.DO.FindInBatches(result, batchSize, fc)
}

func (b barData12hDo) Attrs(attrs ...field.AssignExpr) IBarData12hDo {
	return b.withDO(b.DO.Attrs(attrs...))
}

func (b barData12hDo) Assign(attrs ...field.AssignExpr) IBarData12hDo {
	return b.withDO(b.DO.Assign(attrs...))
}

func (b barData12hDo) Joins(fields ...field.RelationField) IBarData12hDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Joins(_f))
	}
	return &b
}

func (b barData12hDo) Preload(fields ...field.RelationField) IBarData12hDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Preload(_f))
	}
	return &b
}

func (b barData12hDo) FirstOrInit() (*model.BarData12h, error) {
	if result, err := b.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.BarData12h), nil
	}
}

func (b barData12hDo) FirstOrCreate() (*model.BarData12h, error) {
	if result, err := b.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.BarData12h), nil
	}
}

func (b barData12hDo) FindByPage(offset int, limit int) (result []*model.BarData12h, count int64, err error) {
	result, err = b.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = b.Offset(-1).Limit(-1).Count()
	return
}

func (b barData12hDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = b.Count()
	if err != nil {
		return
	}

	err = b.Offset(offset).Limit(limit).Scan(result)
	return
}

func (b barData12hDo) Scan(result interface{}) (err error) {
	return b.DO.Scan(result)
}

func (b barData12hDo) Delete(models ...*model.BarData12h) (result gen.ResultInfo, err error) {
	return b.DO.Delete(models)
}

func (b *barData12hDo) withDO(do gen.Dao) *barData12hDo {
	b.DO = *do.(*gen.DO)
	return b
}
