// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/ocean386/common/stock_orm/model"
)

func newStockIndustryList(db *gorm.DB, opts ...gen.DOOption) stockIndustryList {
	_stockIndustryList := stockIndustryList{}

	_stockIndustryList.stockIndustryListDo.UseDB(db, opts...)
	_stockIndustryList.stockIndustryListDo.UseModel(&model.StockIndustryList{})

	tableName := _stockIndustryList.stockIndustryListDo.TableName()
	_stockIndustryList.ALL = field.NewAsterisk(tableName)
	_stockIndustryList.ID = field.NewInt64(tableName, "id")
	_stockIndustryList.StockCode = field.NewString(tableName, "stock_code")
	_stockIndustryList.StockName = field.NewString(tableName, "stock_name")
	_stockIndustryList.IndustryCode = field.NewString(tableName, "industry_code")
	_stockIndustryList.IndustryName = field.NewString(tableName, "industry_name")
	_stockIndustryList.CreatedAt = field.NewTime(tableName, "created_at")
	_stockIndustryList.UpdatedAt = field.NewTime(tableName, "updated_at")

	_stockIndustryList.fillFieldMap()

	return _stockIndustryList
}

// stockIndustryList 行业成份股列表-A股
type stockIndustryList struct {
	stockIndustryListDo

	ALL          field.Asterisk
	ID           field.Int64  // 主键ID
	StockCode    field.String // 股票代码
	StockName    field.String // 股票名称
	IndustryCode field.String // 行业代码
	IndustryName field.String // 行业名称
	CreatedAt    field.Time   // 创建时间
	UpdatedAt    field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (s stockIndustryList) Table(newTableName string) *stockIndustryList {
	s.stockIndustryListDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s stockIndustryList) As(alias string) *stockIndustryList {
	s.stockIndustryListDo.DO = *(s.stockIndustryListDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *stockIndustryList) updateTableName(table string) *stockIndustryList {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.StockCode = field.NewString(table, "stock_code")
	s.StockName = field.NewString(table, "stock_name")
	s.IndustryCode = field.NewString(table, "industry_code")
	s.IndustryName = field.NewString(table, "industry_name")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")

	s.fillFieldMap()

	return s
}

func (s *stockIndustryList) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *stockIndustryList) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 7)
	s.fieldMap["id"] = s.ID
	s.fieldMap["stock_code"] = s.StockCode
	s.fieldMap["stock_name"] = s.StockName
	s.fieldMap["industry_code"] = s.IndustryCode
	s.fieldMap["industry_name"] = s.IndustryName
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
}

func (s stockIndustryList) clone(db *gorm.DB) stockIndustryList {
	s.stockIndustryListDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s stockIndustryList) replaceDB(db *gorm.DB) stockIndustryList {
	s.stockIndustryListDo.ReplaceDB(db)
	return s
}

type stockIndustryListDo struct{ gen.DO }

type IStockIndustryListDo interface {
	gen.SubQuery
	Debug() IStockIndustryListDo
	WithContext(ctx context.Context) IStockIndustryListDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IStockIndustryListDo
	WriteDB() IStockIndustryListDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IStockIndustryListDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IStockIndustryListDo
	Not(conds ...gen.Condition) IStockIndustryListDo
	Or(conds ...gen.Condition) IStockIndustryListDo
	Select(conds ...field.Expr) IStockIndustryListDo
	Where(conds ...gen.Condition) IStockIndustryListDo
	Order(conds ...field.Expr) IStockIndustryListDo
	Distinct(cols ...field.Expr) IStockIndustryListDo
	Omit(cols ...field.Expr) IStockIndustryListDo
	Join(table schema.Tabler, on ...field.Expr) IStockIndustryListDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IStockIndustryListDo
	RightJoin(table schema.Tabler, on ...field.Expr) IStockIndustryListDo
	Group(cols ...field.Expr) IStockIndustryListDo
	Having(conds ...gen.Condition) IStockIndustryListDo
	Limit(limit int) IStockIndustryListDo
	Offset(offset int) IStockIndustryListDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IStockIndustryListDo
	Unscoped() IStockIndustryListDo
	Create(values ...*model.StockIndustryList) error
	CreateInBatches(values []*model.StockIndustryList, batchSize int) error
	Save(values ...*model.StockIndustryList) error
	First() (*model.StockIndustryList, error)
	Take() (*model.StockIndustryList, error)
	Last() (*model.StockIndustryList, error)
	Find() ([]*model.StockIndustryList, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.StockIndustryList, err error)
	FindInBatches(result *[]*model.StockIndustryList, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.StockIndustryList) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IStockIndustryListDo
	Assign(attrs ...field.AssignExpr) IStockIndustryListDo
	Joins(fields ...field.RelationField) IStockIndustryListDo
	Preload(fields ...field.RelationField) IStockIndustryListDo
	FirstOrInit() (*model.StockIndustryList, error)
	FirstOrCreate() (*model.StockIndustryList, error)
	FindByPage(offset int, limit int) (result []*model.StockIndustryList, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IStockIndustryListDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s stockIndustryListDo) Debug() IStockIndustryListDo {
	return s.withDO(s.DO.Debug())
}

func (s stockIndustryListDo) WithContext(ctx context.Context) IStockIndustryListDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s stockIndustryListDo) ReadDB() IStockIndustryListDo {
	return s.Clauses(dbresolver.Read)
}

func (s stockIndustryListDo) WriteDB() IStockIndustryListDo {
	return s.Clauses(dbresolver.Write)
}

func (s stockIndustryListDo) Session(config *gorm.Session) IStockIndustryListDo {
	return s.withDO(s.DO.Session(config))
}

func (s stockIndustryListDo) Clauses(conds ...clause.Expression) IStockIndustryListDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s stockIndustryListDo) Returning(value interface{}, columns ...string) IStockIndustryListDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s stockIndustryListDo) Not(conds ...gen.Condition) IStockIndustryListDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s stockIndustryListDo) Or(conds ...gen.Condition) IStockIndustryListDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s stockIndustryListDo) Select(conds ...field.Expr) IStockIndustryListDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s stockIndustryListDo) Where(conds ...gen.Condition) IStockIndustryListDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s stockIndustryListDo) Order(conds ...field.Expr) IStockIndustryListDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s stockIndustryListDo) Distinct(cols ...field.Expr) IStockIndustryListDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s stockIndustryListDo) Omit(cols ...field.Expr) IStockIndustryListDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s stockIndustryListDo) Join(table schema.Tabler, on ...field.Expr) IStockIndustryListDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s stockIndustryListDo) LeftJoin(table schema.Tabler, on ...field.Expr) IStockIndustryListDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s stockIndustryListDo) RightJoin(table schema.Tabler, on ...field.Expr) IStockIndustryListDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s stockIndustryListDo) Group(cols ...field.Expr) IStockIndustryListDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s stockIndustryListDo) Having(conds ...gen.Condition) IStockIndustryListDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s stockIndustryListDo) Limit(limit int) IStockIndustryListDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s stockIndustryListDo) Offset(offset int) IStockIndustryListDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s stockIndustryListDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IStockIndustryListDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s stockIndustryListDo) Unscoped() IStockIndustryListDo {
	return s.withDO(s.DO.Unscoped())
}

func (s stockIndustryListDo) Create(values ...*model.StockIndustryList) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s stockIndustryListDo) CreateInBatches(values []*model.StockIndustryList, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s stockIndustryListDo) Save(values ...*model.StockIndustryList) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s stockIndustryListDo) First() (*model.StockIndustryList, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.StockIndustryList), nil
	}
}

func (s stockIndustryListDo) Take() (*model.StockIndustryList, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.StockIndustryList), nil
	}
}

func (s stockIndustryListDo) Last() (*model.StockIndustryList, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.StockIndustryList), nil
	}
}

func (s stockIndustryListDo) Find() ([]*model.StockIndustryList, error) {
	result, err := s.DO.Find()
	return result.([]*model.StockIndustryList), err
}

func (s stockIndustryListDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.StockIndustryList, err error) {
	buf := make([]*model.StockIndustryList, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s stockIndustryListDo) FindInBatches(result *[]*model.StockIndustryList, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s stockIndustryListDo) Attrs(attrs ...field.AssignExpr) IStockIndustryListDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s stockIndustryListDo) Assign(attrs ...field.AssignExpr) IStockIndustryListDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s stockIndustryListDo) Joins(fields ...field.RelationField) IStockIndustryListDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s stockIndustryListDo) Preload(fields ...field.RelationField) IStockIndustryListDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s stockIndustryListDo) FirstOrInit() (*model.StockIndustryList, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.StockIndustryList), nil
	}
}

func (s stockIndustryListDo) FirstOrCreate() (*model.StockIndustryList, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.StockIndustryList), nil
	}
}

func (s stockIndustryListDo) FindByPage(offset int, limit int) (result []*model.StockIndustryList, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s stockIndustryListDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s stockIndustryListDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s stockIndustryListDo) Delete(models ...*model.StockIndustryList) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *stockIndustryListDo) withDO(do gen.Dao) *stockIndustryListDo {
	s.DO = *do.(*gen.DO)
	return s
}
