// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameStockIndustryList = "stock_industry_list"

// StockIndustryList 行业成份股列表-A股
type StockIndustryList struct {
	ID           int64     `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true;comment:主键ID" json:"id"` // 主键ID
	StockCode    string    `gorm:"column:stock_code;type:varchar(10);not null;comment:股票代码" json:"stock_code"`              // 股票代码
	StockName    string    `gorm:"column:stock_name;type:varchar(50);not null;comment:股票名称" json:"stock_name"`              // 股票名称
	IndustryCode string    `gorm:"column:industry_code;type:varchar(10);not null;comment:行业代码" json:"industry_code"`        // 行业代码
	IndustryName string    `gorm:"column:industry_name;type:varchar(50);not null;comment:行业名称" json:"industry_name"`        // 行业名称
	CreatedAt    time.Time `gorm:"column:created_at;comment:创建时间" json:"created_at"`                                        // 创建时间
	UpdatedAt    time.Time `gorm:"column:updated_at;autoUpdateTime:mill;comment:更新时间" json:"updated_at"`                    // 更新时间
}

// TableName StockIndustryList's table name
func (*StockIndustryList) TableName() string {
	return TableNameStockIndustryList
}
