// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCurencyTicker = "curency_ticker"

// CurencyTicker 行情数据-订阅币种表
type CurencyTicker struct {
	ID         int64  `gorm:"column:id;type:bigint(20);primaryKey;autoIncrement:true;comment:主键ID" json:"id"` // 主键ID
	CurrencyID string `gorm:"column:currency_id;type:varchar(10);not null;comment:币种ID" json:"currency_id"`   // 币种ID
	Status     int64  `gorm:"column:status;type:tinyint(8);not null;comment:订阅状态: 0-未订阅 1-已订阅" json:"status"` // 订阅状态: 0-未订阅 1-已订阅
	Spot       int64  `gorm:"column:spot;type:tinyint(8);not null;comment:订阅状态: 0-现货 1-合约" json:"spot"`       // 订阅状态: 0-现货 1-合约
	CreatedAt  int64  `gorm:"column:created_at;comment:创建时间" json:"created_at"`                               // 创建时间
	UpdatedAt  int64  `gorm:"column:updated_at;autoUpdateTime:mill;comment:更新时间" json:"updated_at"`           // 更新时间
}

// TableName CurencyTicker's table name
func (*CurencyTicker) TableName() string {
	return TableNameCurencyTicker
}
