// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDailyDatum = "daily_data"

// DailyDatum 虚拟币历史数据表
type DailyDatum struct {
	ID                int64   `gorm:"column:id;type:bigint(20);primaryKey;comment:主键ID" json:"id"`                                                    // 主键ID
	CurrencyID        string  `gorm:"column:currency_id;type:varchar(10);not null;comment:币种ID" json:"currency_id"`                                   // 币种ID
	OpenPrice         float64 `gorm:"column:open_price;type:decimal(10,3);not null;default:0.000;comment:开盘价格-亚洲" json:"open_price"`                  // 开盘价格-亚洲
	ClosePrice        float64 `gorm:"column:close_price;type:decimal(10,3);not null;default:0.000;comment:最新成交价格|每日最终收盘价格" json:"close_price"`        // 最新成交价格|每日最终收盘价格
	HighPrice         float64 `gorm:"column:high_price;type:decimal(10,3);not null;default:0.000;comment:最高价" json:"high_price"`                      // 最高价
	LowPrice          float64 `gorm:"column:low_price;type:decimal(10,3);not null;default:0.000;comment:最低价" json:"low_price"`                        // 最低价
	Volume24h         int64   `gorm:"column:volume24h;type:bigint(20);not null;comment:24小时成交量-千亿规模" json:"volume24h"`                                // 24小时成交量-千亿规模
	Timestamp         int64   `gorm:"column:timestamp;type:bigint(20);not null;comment:时间戳" json:"timestamp"`                                         // 时间戳
	SigType           int64   `gorm:"column:sig_type;type:tinyint(8);not null;comment:行情信号:0-/,1-上涨,2-快速上涨,3-爆涨,4-下跌,5-快速下跌,6-爆跌" json:"sig_type"`    // 行情信号:0-/,1-上涨,2-快速上涨,3-爆涨,4-下跌,5-快速下跌,6-爆跌
	PriceChange       float64 `gorm:"column:price_change;type:decimal(10,3);not null;default:0.000;comment:涨跌幅度" json:"price_change"`                 // 涨跌幅度
	PriceRange        float64 `gorm:"column:price_range;type:decimal(10,3);not null;default:0.000;comment:涨跌振幅" json:"price_range"`                   // 涨跌振幅
	PriceRangePrecent float64 `gorm:"column:price_range_precent;type:decimal(10,3);not null;default:0.000;comment:涨跌振幅比例" json:"price_range_precent"` // 涨跌振幅比例
	TriggerTime       int64   `gorm:"column:trigger_time;type:bigint(20);not null;comment:触发时间" json:"trigger_time"`                                  // 触发时间
	CreateTime        int64   `gorm:"column:create_time;type:bigint(20);not null;comment:插入记录-时间" json:"create_time"`                                 // 插入记录-时间
	ProductType       string  `gorm:"column:product_type;type:varchar(10);not null;default:SPOT;comment:产品类型: 默认值SPOT" json:"product_type"`           // 产品类型: 默认值SPOT
}

// TableName DailyDatum's table name
func (*DailyDatum) TableName() string {
	return TableNameDailyDatum
}
