// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMonitorDatum = "monitor_data"

// MonitorDatum 监控行情数据指标表
type MonitorDatum struct {
	ID         int64   `gorm:"column:id;type:bigint(20);primaryKey;comment:主键ID" json:"id"`                                                             // 主键ID
	CurrencyID string  `gorm:"column:currency_id;type:varchar(20);not null;comment:币种ID" json:"currency_id"`                                            // 币种ID
	BarType    string  `gorm:"column:bar_type;type:varchar(10);not null;default:1M;comment:时间粒度类型:默认值1m,1m/5m/15m/30m/1H/4H/12H/1D/1W" json:"bar_type"` // 时间粒度类型:默认值1m,1m/5m/15m/30m/1H/4H/12H/1D/1W
	EmaPrice   float64 `gorm:"column:ema_price;type:decimal(18,3);not null;default:0.000;comment:收盘价-指数移动平均线-EMA" json:"ema_price"`                     // 收盘价-指数移动平均线-EMA
	HighPrice  float64 `gorm:"column:high_price;type:decimal(18,3);not null;default:0.000;comment:最高价格-根据时间粒度" json:"high_price"`                       // 最高价格-根据时间粒度
	LowPrice   float64 `gorm:"column:low_price;type:decimal(18,3);not null;default:0.000;comment:最低价格-根据时间粒度" json:"low_price"`                         // 最低价格-根据时间粒度
	UpdateTime int64   `gorm:"column:update_time;type:bigint(20);not null;comment:更新时间" json:"update_time"`                                             // 更新时间
}

// TableName MonitorDatum's table name
func (*MonitorDatum) TableName() string {
	return TableNameMonitorDatum
}
