// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameOrderEvent = "order_event"

// OrderEvent 订单成交事件
type OrderEvent struct {
	ID          int64   `gorm:"column:id;type:bigint(20);primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                     // 主键ID
	OrderCid    string  `gorm:"column:order_cid;type:varchar(20);not null;comment:客户自定义订单ID" json:"order_cid"`                      // 客户自定义订单ID
	OrderPid    string  `gorm:"column:order_pid;type:varchar(20);not null;comment:OK平台订单ID" json:"order_pid"`                       // OK平台订单ID
	CurrencyID  string  `gorm:"column:currency_id;type:varchar(10);not null;comment:币种ID" json:"currency_id"`                       // 币种ID
	Simulation  int64   `gorm:"column:simulation;type:tinyint(8);not null;default:1;comment:模拟订单: 0-全部,1-否, 2-是" json:"simulation"` // 模拟订单: 0-全部,1-否, 2-是
	OrderStatus int64   `gorm:"column:order_status;type:tinyint(8);not null;comment:订单状态:" json:"order_status"`                     // 订单状态:
	Filled      float64 `gorm:"column:filled;type:decimal(12,4);not null;default:0.0000;comment:交易数量" json:"filled"`                // 交易数量
	FillPrice   float64 `gorm:"column:fill_price;type:decimal(12,4);not null;default:0.0000;comment:交易价格" json:"fill_price"`        // 交易价格
	Fee         float64 `gorm:"column:fee;type:decimal(12,6);not null;default:0.000000;comment:手续费" json:"fee"`                     // 手续费
	FilledAt    int64   `gorm:"column:filled_at;type:bigint(20);not null;comment:成交时间" json:"filled_at"`                            // 成交时间
	TableName_  string  `gorm:"column:table_name;type:varchar(20);not null;comment:订单所对应表名" json:"table_name"`                      // 订单所对应表名
}

// TableName OrderEvent's table name
func (*OrderEvent) TableName() string {
	return TableNameOrderEvent
}
