// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSpotGrid = "spot_grid"

// SpotGrid 网格列表-现货
type SpotGrid struct {
	ID                   int64   `gorm:"column:id;type:bigint(20);primaryKey;comment:主键ID" json:"id"`                                                                    // 主键ID
	GridID               string  `gorm:"column:grid_id;type:varchar(20);not null;comment:网格ID" json:"grid_id"`                                                           // 网格ID
	UserID               int64   `gorm:"column:user_id;type:int(11);not null;default:10000;comment:用户ID" json:"user_id"`                                                 // 用户ID
	CurrencyID           string  `gorm:"column:currency_id;type:varchar(10);not null;comment:币种ID" json:"currency_id"`                                                   // 币种ID
	Simulation           int64   `gorm:"column:simulation;type:tinyint(8);not null;default:1;comment:模拟订单: 0-全部,1-否, 2-是" json:"simulation"`                             // 模拟订单: 0-全部,1-否, 2-是
	TriggerBuySellType   int64   `gorm:"column:trigger_buy_sell_type;type:tinyint(8);not null;comment:触发买卖: 0-全部,1-买入,2-卖出 3-不建仓" json:"trigger_buy_sell_type"`          // 触发买卖: 0-全部,1-买入,2-卖出 3-不建仓
	GridStatus           int64   `gorm:"column:grid_status;type:tinyint(8);not null;comment:网格状态:0-全部,1-等待触发,2-已暂停,3-正在运行,4-停止&不平仓,5-停止&平仓,6-已撤销" json:"grid_status"`    // 网格状态:0-全部,1-等待触发,2-已暂停,3-正在运行,4-停止&不平仓,5-停止&平仓,6-已撤销
	TransactionType      int64   `gorm:"column:transaction_type;type:tinyint(8);not null;default:1;comment:交易模式: 0-全部,1-正常买卖,2-特价买卖(卖高特价,买低特价)" json:"transaction_type"` // 交易模式: 0-全部,1-正常买卖,2-特价买卖(卖高特价,买低特价)
	ImmediateTrigger     int64   `gorm:"column:immediate_trigger;type:tinyint(8);not null;default:1;comment:立即触发: 0-全部,1-否, 2-是" json:"immediate_trigger"`               // 立即触发: 0-全部,1-否, 2-是
	TriggerGridPrice     float64 `gorm:"column:trigger_grid_price;type:decimal(12,4);not null;default:0.0000;comment:触发价格" json:"trigger_grid_price"`                    // 触发价格
	SpecialPrice         float64 `gorm:"column:special_price;type:decimal(12,4);not null;default:0.0000;comment:特殊价格" json:"special_price"`                              // 特殊价格
	MinPrice             float64 `gorm:"column:min_price;type:decimal(12,4);not null;default:0.0000;comment:最低价格" json:"min_price"`                                      // 最低价格
	MaxPrice             float64 `gorm:"column:max_price;type:decimal(12,4);not null;default:0.0000;comment:最高价格" json:"max_price"`                                      // 最高价格
	MinStopPrice         float64 `gorm:"column:min_stop_price;type:decimal(12,4);not null;default:0.0000;comment:最低停止价格" json:"min_stop_price"`                          // 最低停止价格
	MaxStopPrice         float64 `gorm:"column:max_stop_price;type:decimal(12,4);not null;default:0.0000;comment:最高停止价格" json:"max_stop_price"`                          // 最高停止价格
	GridEqualPriceFirst  float64 `gorm:"column:grid_equal_price_first;type:decimal(12,4);not null;default:0.0000;comment:网格差价-主" json:"grid_equal_price_first"`          // 网格差价-主
	GridEqualPriceSecond float64 `gorm:"column:grid_equal_price_second;type:decimal(12,4);not null;default:0.0000;comment:网格差价-次" json:"grid_equal_price_second"`        // 网格差价-次
	GridNumber           int64   `gorm:"column:grid_number;type:int(11);not null;default:2;comment:网格数量" json:"grid_number"`                                             // 网格数量
	GridCurrencyNumber   float64 `gorm:"column:grid_currency_number;type:decimal(12,4);not null;default:0.0000;comment:币种数量" json:"grid_currency_number"`                // 币种数量
	CurrencyPosition     float64 `gorm:"column:currency_position;type:decimal(12,4);not null;default:0.0000;comment:持仓数量" json:"currency_position"`                      // 持仓数量
	ProfitAmount         float64 `gorm:"column:profit_amount;type:decimal(12,4);not null;default:0.0000;comment:盈亏金额" json:"profit_amount"`                              // 盈亏金额
	ProfitPercent        float64 `gorm:"column:profit_percent;type:decimal(12,4);not null;default:0.0000;comment:盈亏比例" json:"profit_percent"`                            // 盈亏比例
	FilledTimes          float64 `gorm:"column:filled_times;type:decimal(12,4);not null;default:0.0000;comment:成交次数" json:"filled_times"`                                // 成交次数
	GridProfitAmount     float64 `gorm:"column:grid_profit_amount;type:decimal(12,4);not null;default:0.0000;comment:网格收益" json:"grid_profit_amount"`                    // 网格收益
	InitAmount           float64 `gorm:"column:init_amount;type:decimal(12,4);not null;default:0.0000;comment:初始金额-USDT" json:"init_amount"`                             // 初始金额-USDT
	Fee                  float64 `gorm:"column:fee;type:decimal(12,6);not null;default:0.000000;comment:手续费" json:"fee"`                                                 // 手续费
	CreatedAt            int64   `gorm:"column:created_at;comment:创建时间" json:"created_at"`                                                                               // 创建时间
	UpdatedAt            int64   `gorm:"column:updated_at;autoUpdateTime:mill;comment:更新时间" json:"updated_at"`                                                           // 更新时间
}

// TableName SpotGrid's table name
func (*SpotGrid) TableName() string {
	return TableNameSpotGrid
}
