// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSpotGridOrder = "spot_grid_order"

// SpotGridOrder 网格订单-现货
type SpotGridOrder struct {
	ID             int64   `gorm:"column:id;type:bigint(20);primaryKey;comment:主键ID" json:"id"`                                                                       // 主键ID
	GridID         string  `gorm:"column:grid_id;type:varchar(20);not null;comment:网格ID" json:"grid_id"`                                                              // 网格ID
	OrderCid       string  `gorm:"column:order_cid;type:varchar(20);not null;comment:客户自定义订单ID" json:"order_cid"`                                                     // 客户自定义订单ID
	OrderPid       string  `gorm:"column:order_pid;type:varchar(20);not null;comment:OK平台订单ID" json:"order_pid"`                                                      // OK平台订单ID
	UserID         int64   `gorm:"column:user_id;type:int(11);not null;default:10000;comment:用户ID" json:"user_id"`                                                    // 用户ID
	CurrencyID     string  `gorm:"column:currency_id;type:varchar(10);not null;comment:币种ID" json:"currency_id"`                                                      // 币种ID
	Simulation     int64   `gorm:"column:simulation;type:tinyint(8);not null;default:1;comment:模拟订单: 0-全部,1-否, 2-是" json:"simulation"`                                // 模拟订单: 0-全部,1-否, 2-是
	BuySellType    int64   `gorm:"column:buy_sell_type;type:tinyint(8);not null;comment:交易方向: 0-全部,1-买入,2-卖出,3-完成买卖" json:"buy_sell_type"`                            // 交易方向: 0-全部,1-买入,2-卖出,3-完成买卖
	OrderStatus    int64   `gorm:"column:order_status;type:tinyint(8);not null;comment:订单状态:0-全部,1-等待提交,2-已暂停,3-等待成交,4-部分成交,5-买卖成交,6-完全成交,7-已撤销" json:"order_status"` // 订单状态:0-全部,1-等待提交,2-已暂停,3-等待成交,4-部分成交,5-买卖成交,6-完全成交,7-已撤销
	OrderType      int64   `gorm:"column:order_type;type:tinyint(8);not null;default:1;comment:交易类型: 0-全部,1-高级限价,2-限价委托,3-市价委托" json:"order_type"`                    // 交易类型: 0-全部,1-高级限价,2-限价委托,3-市价委托
	Total          float64 `gorm:"column:total;type:decimal(12,4);not null;default:0.0000;comment:交易数量" json:"total"`                                                 // 交易数量
	OrderPriceBuy  float64 `gorm:"column:order_price_buy;type:decimal(12,4);not null;default:0.0000;comment:交易价格-买入" json:"order_price_buy"`                          // 交易价格-买入
	OrderPriceSell float64 `gorm:"column:order_price_sell;type:decimal(12,4);not null;default:0.0000;comment:交易价格-卖出" json:"order_price_sell"`                        // 交易价格-卖出
	TotalAmount    float64 `gorm:"column:total_amount;type:decimal(12,4);not null;default:0.0000;comment:交易金额" json:"total_amount"`                                   // 交易金额
	ProfitAmount   float64 `gorm:"column:profit_amount;type:decimal(12,4);not null;default:0.0000;comment:盈亏金额" json:"profit_amount"`                                 // 盈亏金额
	Fee            float64 `gorm:"column:fee;type:decimal(12,6);not null;default:0.000000;comment:手续费" json:"fee"`                                                    // 手续费
	CreatedAt      int64   `gorm:"column:created_at;comment:创建时间" json:"created_at"`                                                                                  // 创建时间
	FilledAt       int64   `gorm:"column:filled_at;type:bigint(20);not null;comment:成交时间" json:"filled_at"`                                                           // 成交时间
	CanceledAt     int64   `gorm:"column:canceled_at;type:bigint(20);not null;comment:撤销时间" json:"canceled_at"`                                                       // 撤销时间
}

// TableName SpotGridOrder's table name
func (*SpotGridOrder) TableName() string {
	return TableNameSpotGridOrder
}
